# API for the Azure Machine Learning service ML service
###
# Health check
GET https://refundprediction-xyyjr.eastus2.inference.ml.azure.com/ HTTP/1.1
Authorization: Bearer 6lbmCZL0FeMYIiIDf2lIzIdRgEi2SDh83qls87HEsEoG65z1uBKlJQQJ99BLAAAAAAAAAAAAINFRAZML3LqK

###
# Swagger documentation
GET https://refundprediction-xyyjr.eastus2.inference.ml.azure.com/swagger.json HTTP/1.1 
Authorization: Bearer 6lbmCZL0FeMYIiIDf2lIzIdRgEi2SDh83qls87HEsEoG65z1uBKlJQQJ99BLAAAAAAAAAAAAINFRAZML3LqK

###
# get ETA prediction output
POST https://refundprediction-xyyjr.eastus2.inference.ml.azure.com/score HTTP/1.1
Content-Type: application/json
Authorization: Bearer 6lbmCZL0FeMYIiIDf2lIzIdRgEi2SDh83qls87HEsEoG65z1uBKlJQQJ99BLAAAAAAAAAAAAINFRAZML3LqK

{
  "input_data": {
    "columns": [
      "Filing_ID",
      "Filing_Method",
      "Submission_Date",
      "Return_Complexity",
      "Errors_Flag",
      "Refund_Type",
      "IRS_Backlog_Flag",
      "Bank_Deposit_Method",
      "Refund_Amount",
      "Return_Complexity_Score",
      "Seasonal_Filing_Indicator",
      "Filing_Day_Of_Week",
      "Refund_Amount_Bucket",
      "Error_Severity_Score"
    ],
    "index": [0],
    "data": [
      [
        12345,
        "E-File",
        "2025-03-15",
        "Medium",
        "No",
        "Direct Deposit",
        "No",
        "ACH",
        1500,
        2,
        1,
        "Wednesday",
        "Medium",
        0
      ]     
    ]
  }
}


